connection:
  url: "https://ruslan.library.spbstu.ru/rrs-web/db/"
  db: "EBOOKS"
  query: "(dc.type=\"Academic thesis\")and(dc.language=rus)"
  fcq:
  download_list_maxsize: 100
  download_batch_size: 10
output:
  common_dir: "output"
  samples_dir: "samples"
auth:
  .ASPXAUTH:
  ASP.NET_SessionId:
